# Generated by Django 6.0 on 2025-12-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='listing',
            name='unique_owner_full_address',
        ),
        migrations.AlterField(
            model_name='listing',
            name='house_suffix',
            field=models.CharField(blank=True, help_text='Addition to the house number (e.g. A, B, courtyard apartment, app 12, etc.)', max_length=20, verbose_name='House suffix'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(fields=('street', 'house_number', 'house_suffix', 'postal_code', 'city', 'listing_type'), name='unique_property_by_address'),
        ),
    ]
