# Generated by Django 6.0 on 2025-12-11 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_remove_listing_unique_owner_full_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='house_suffix',
            field=models.CharField(blank=True, help_text='Addition to the house number (e.g. A, B, courtyard apartment, app 12, etc.).', max_length=20, verbose_name='House suffix'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rate from 1 (poor) to 5 (excellent) stars.', verbose_name='Rating'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('listing', 'author'), name='unique_review_per_listing_author'),
        ),
    ]
