# Generated by Django 6.0 on 2025-12-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_alter_listing_house_suffix_alter_review_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='region',
            field=models.CharField(blank=True, help_text='Federal state or region in Germany (e.g. Bavaria, NRW).', max_length=100, null=True, verbose_name='Region'),
        ),
    ]
